### ISSUE TITLE
Index website

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/eva#35]
For website indexing...

**Comment by amihaiemil** [comment]
@charlesmike index this site please

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://decorators-squad.github.io/eva/sitemap.xml) sitemap please.

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://decorators-squad.github.io/eva/sitemap.xml) sitemap please.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/2bb251bd-2ddc-4de1-9991-c2ae9c17f67c.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://decorators-squad.github.io/eva/sitemap.xml) sitemap please.

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/2bb251bd-2ddc-4de1-9991-c2ae9c17f67c.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
